### ISSUE TITLE
Segmentation fault in test when node_publisher writes sample2

### ISSUE THREAD

**Issue by JuneZA** [oci-labs/node-opendds#17]
It seems that this happens when the 'mu' (union field) of the sample is populated with the fourth option of the union, which is a nested string sequence type.

When I modify sample2 of the node_publisher to make use of any of the other options, the sample is written successfully.

**Comment by simpsont-oci** [comment]
What version of OpenDDS are you running with and what platform are you on?

**Comment by JuneZA** [comment]
I am running Ubuntu 18.04.3, and the OpenDDS version > 3.13. (I have the master branch from sometime after 3.13 was released.)

**Comment by simpsont-oci** [comment]
We fixed some v8_generator issues back in August which should also be in master (commits cdcd1dc584bdcef7ff21b1f19cf8a17e76017c1d, 4aa1d0e1b7f9ea1955f94cd04684727c5a638759). Can you try to pull the latest master and retest? There have been a few changes to IDL generation that you might need to work through, but hopefully nothing too difficult.
