### ISSUE TITLE
Latest version is not published on npm

### ISSUE THREAD

**Issue by ebakoba** [oci-labs/node-opendds#18]
It seems that latest version of this library's master branch has not been released on `npm`. The `npm` version for example does not contain `create_datawriter` function.

**Comment by iguessthislldo** [comment]
It looks like we haven't made a release with the publishing support yet, so technically npm does have the latest version. I get what you mean though. At least by the looks of the CI, it looks like this code isn't in a release-able state. We would have to fix that before pushing out a new version.

**Comment by simpsont-oci** [comment]
https://github.com/oci-labs/node-opendds/releases/tag/v0.1.0
