### ISSUE TITLE
Error when trying to install node-opendds

### ISSUE THREAD

**Issue by mateidediu** [oci-labs/node-opendds#2]
I tried installing node-opendds after building opendds (build successful). Ran into this error: 
`|

> opendds@0.0.4 install C:\node_modules\opendds
> node-gyp rebuild

C:\node_modules\opendds>node "C:\Program Files\nodejs\node_modules\npm\bin\node-
gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp: Undefined variable lib_suffix in binding.gyp while trying to load binding.g
yp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:
12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\node_modules\opendds
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! opendds@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opendds@0.0.4 install script.
npm ERR! This is most likely a problem with the opendds package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls opendds
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "opendds"
npm ERR! cwd C:\
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0`

My npm version is 1.4.28 and my node version 0.10.38, running on windows 8 64-bit. 
Read this issue https://github.com/oci-labs/node-opendds/issues/1 but it's rather unclear what i should do in order to get this to work.

Thank you,
Matei

**Comment by mitza-oci** [comment]
The result of issue #1 is that Node.js broke compatibility since version 0.8.  Please see issue #1 for the versions of Node and v8 we used to develop this addon, and a path forward to compatibility with modern versions.  And do let us know if you can help enhance node-opendds.

**Comment by mitza-oci** [comment]
Issue #4 is fixed, this module is now working with the current version of Node.js.

**Comment by toastchee** [comment]
for this error on windows:

**Undefined variable lib_suffix in binding.gyp while trying to load binding.gyp**

Open the binding.gyp file and change the last part to: 

```
        ['OS=="win"', {
          'msvs_settings' : {
            'VCLinkerTool': {
              'AdditionalLibraryDirectories': [ '$(ACE_ROOT)/lib',
                                                '$(DDS_ROOT)/lib' ],
            },
          },
          'link_settings': {
            'libraries': [ 'OpenDDS_Dcpsd.dll',
                           'TAO_PortableServerd.dll',
                           'TAO_AnyTypeCoded.dll',
                           'TAOd.dll', 'ACEd.dll' ],
          },
        }]
```

**Comment by mitza-oci** [comment]
@toastchee binding.gyp variables are set on the `npm install` command line.  See the README in https://github.com/oci-labs/iiot-demo-opendds for an example.  If that doesn't work please open a new issue with all the steps required to reproduce the error you're seeing.
