### ISSUE TITLE
Everything hangs when creating subscribers/datawriters

### ISSUE THREAD

**Issue by sanderkukk** [oci-labs/node-opendds#20]
I'm using the latest master (as of writing this)  from `OpenDDS` and using `node-opendds 0.1.0`. 

My library is found and participant is created successfully.
Problems arise afterwards when using `subscribe` or `create_datawriter` - after that everything seemingly hangs. 
I enabled the `-DCPSDebugLevel 10` parameter.

After calling `subscribe` this line is printed 
`(4450|4450) Service_Participant::get_discovery: returning repository for domain 50, repo uni_rtps.`
and nothing more is happening. My entire application becomes unresponsive and will not work until hard reset.

Because this setup has worked before, the latest that I know of 13. October. I made a openDDS checkout back to ` 2550e2654208f1ce382b71ad8a0075b7f2152a8f`. Recompiled and everything is working properly. 
Do you know of any changes between those dates that may affect my use-case or do you have any ideas I could troubleshoot this further?

**Comment by ebakoba** [comment]
Please help

**Comment by ebakoba** [comment]
Ping
