### ISSUE TITLE
Implement "messenger" subscriber in Node.js 

### ISSUE THREAD

**Issue by aditya-krish** [oci-labs/node-opendds#22]
The messenger publisher and subscriber are the most common test for OpenDDS, I tried to implement a Node.js subscriber for the Publisher given in the OpenDDS installation. I have uploaded my code in this repository: https://github.com/aditya-krish/NodeJSMessenger . I am not able to match the Messenger publisher with this subscriber. What is the issue? What am I missing?

This is the relevant subscriber.js (all the files are also in the repository linked):
```
"use strict";

var DOMAIN_ID = 42;

var qos = {user_data: 'foo'};

function init_opendds(opendds_addon) {
    return opendds_addon.initialize('-DCPSConfigFile', 'rtps.ini');
}

var opendds_addon = require('opendds/lib/node-opendds'),
  factory = init_opendds(opendds_addon),
  library = opendds_addon.load('idl/messenger_idl_test'),
  participant = factory.create_participant(DOMAIN_ID, qos),
  reader,
  last_sample_id = 39,
  dds_inf = 0x7fffffff,
  infinite = {sec: dds_inf, nanosec: dds_inf};

function log(label, object) {
  console.log(label + ': ' + JSON.stringify(object, null, 2));
}

try {
  if (!library) {
    throw 'Failed to load shared library';
  }
    reader = participant.subscribe('topic', 'Messenger::Message', 
        qos, 
        function (dr, sinfo, sample) {
            try {
            log('Received callback', sample);
            log('Sample Info', sinfo);
            if (sample.count == last_sample_id) {
                participant.unsubscribe(reader);
            
            }
            } catch (e) {
                console.log("Error in callback: " + e);
            }
        }
    );
} catch (e) {
  console.log(e);
}

process.on('exit', function () {
  factory.delete_participant(participant); // optional
  opendds_addon.finalize(factory);
});
```

The publisher uses default QoS settings. It is taken as is from the $DDS_ROOT/java/tests/messenger. To implement said subscriber clone https://github.com/aditya-krish/MessengerTest and follow the README.md

**Comment by simpsont-oci** [comment]
I know this is an old issue, but it's hard to know what might have caused this issue without more detail. Generally, for issues like this, I would suggest making sure you can get OpenDDS applications to work normally before trying to get node-opendds bindings for node.js to work so you know it's not a system config or opendds config issue.
