### ISSUE TITLE
node-gyp error: Undefined variable lib_suffix

### ISSUE THREAD

**Issue by kylenotfound** [oci-labs/node-opendds#26]
Hello,

I am a student at Rowan University in Glassboro New Jersey. I am enrolled in a Software Engineering course in which the semester long project involves my team and I using OpenDDS to create a pub/sub client facing program in c++ in which the publisher can requests queries via the Yelp Fusion API to be returned to the publisher and all subscribers listening. 

I wanted to see if I can utilize this package to interface with my express JS server which will be interacting with the Yelp API.
I am having trouble running "npm i opendds" and am receiving similar errors that folks in other issues posted here are having. 

I am running Windows 10 64 Pro, NPM 6.14.12, Node v14.16.1.
Attached is a screen cap of my issue. Any advice, in any regard to the state of this repo would be appreciated. 

![opendds issue](https://user-images.githubusercontent.com/55156513/134730923-ff6a6f53-ac40-42f1-9daf-d3efefcaff6c.JPG)

Thank you
-Kyle

**Comment by mitza-oci** [comment]
Which OpenDDS version are you using?
There's a lib_suffix variable that it's complaining about (in the future please copy/paste text and not images so it's searchable).  For Windows / Visual C++ you need to provide that variable's definition to node-gyp.

**Comment by kylenotfound** [comment]
Thanks for your reply, and noted on the screen caps. 

I have configured and built OpenDDS-**3.18**.
As for the "lib_suffix" variable definition, it does not appear to be set when running setenv.cmd. Is this another variable that needs to be manually set, and if so where/how? 

If it's definition is located in the OpenDDS directory, what is the typical path for it and with what command options should be used when running npm i opendds

I copy/pasted my setenv.cmd if that is helpful for you.

*My setenv.cmd*
S:\Code\OpenDDS-3.18\OpenDDS-3.18>more setenv.cmd
:: OpenDDS configure script: configure
set DDS_ROOT=S:\Code\OpenDDS-3.18\OpenDDS-3.18
set ACE_ROOT=S:\Code\OpenDDS-3.18\OpenDDS-3.18\ACE_wrappers
set MPC_ROOT=S:\Code\OpenDDS-3.18\OpenDDS-3.18\ACE_wrappers\MPC
set DANCE_ROOT=unused
set TAO_ROOT=S:\Code\OpenDDS-3.18\OpenDDS-3.18\ACE_wrappers\TAO
set PATH=%PATH%;S:\Code\OpenDDS-3.18\OpenDDS-3.18\ACE_wrappers\bin;S:\Code\OpenDDS-3.18\OpenDDS-3.18\bin;S:\Code\OpenDDS-3.18\OpenDDS-3.18\ACE_wrappers\lib;S:\Code\OpenDDS-3.18\OpenDDS-3.18\lib
set CIAO_ROOT=unused

Thanks.

**Comment by mitza-oci** [comment]
lib_suffix is a variable in node-gyp, not an environment variable.  I think we have an example of using it somewhere, I can check for it later.

Based on what's currently running in GitHub Actions, try using OpenDDS version 3.14 (`branch-DDS-3.14`).  If you need any features added after 3.14 we'll have to look at getting the Node module updated.

**Comment by kylenotfound** [comment]
Okay thank you. I'll look into using the other version, and see if I am able to get it working. I am not sure if the project we are making will require any other features from 3.18, my team and I are still new to OpenDDS and learning how it works, reading the Documentation and playing with the Shapes and Messenger Demo. We are also still exploring other options for our small server. We settled on Node and Express because the team has the most knowledge on those, but would you suggest a better alternative, or to try to get node going?

As a student learning your platform, do you have any recommendations or tips that may help our team in developing the project I described in my first message?

**Comment by mitza-oci** [comment]
The README in https://github.com/oci-labs/iiot-demo-opendds has an example of using `lib_suffix` (in step 3).  Perhaps getting this demo built and running would also help answer your question about the integration of an OpenDDS subscriber with Node.js.

**Comment by kylenotfound** [comment]
Thanks, I will take a look into that.

**Comment by simpsont-oci** [comment]
Closing for now. Let us know if you have any further issues.
