### ISSUE TITLE
Support for Node v16

### ISSUE THREAD

**Issue by devamaslan** [oci-labs/node-opendds#36]
I am interested in using node-opendds for a current project being developed using Node v16.14.2. Are you able to give an indicative timeline for the next build release of node-opendds that will provide support for this version of Node?

**Comment by mitza-oci** [comment]
Node.js 16 is in CI https://github.com/oci-labs/node-opendds/runs/5958452856?check_suite_focus=true

Do we just need to do the release version number, tag, and push to npm? @simpsont-oci

**Comment by simpsont-oci** [comment]
This is hopefully resolved now with the v0.1.1 release and publish to npm. Let us know if you encounter any further issues.
