### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by luojinzhang** [oci-labs/node-opendds#42]
Hi guys,
I am trying to install the node-opendds using the readme. However, when I try to do yarn install / npm install. It throws error:
`yarn install v1.22.19
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ node-gyp rebuild

C:\Projects\node-opendds-master\node-opendds-master>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
[##] 2/2gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.22.0 | win32 | x64
gyp info find Python using Python version 2.7.18 found at "C:\Python27\python.exe"
gyp info find VS using VS2015 (14.0) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\laccc\\AppData\\Roaming\\nvm\\v12.22.0\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Projects\\node-opendds-master\\node-opendds-master\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\laccc\\AppData\\Roaming\\nvm\\v12.22.0\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\laccc\\AppData\\Local\\node-gyp\\Cache\\12.22.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\laccc\\AppData\\Local\\node-gyp\\Cache\\12.22.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\laccc\\AppData\\Roaming\\nvm\\v12.22.0\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\laccc\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.22.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Projects\\node-opendds-master\\node-opendds-master',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Projects\\node-opendds-master\\node-opendds-master\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: Undefined variable lib_suffix in binding.gyp while trying to load binding.gyp
←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mconfigure error←[0m
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m Error: `gyp` failed with exit code: 1
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m     at ChildProcess.onCpExit (C:\Users\laccc\AppData\Roaming\nvm\v12.22.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m     at ChildProcess.emit (events.js:314:20)
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mSystem←[0m Windows_NT 10.0.19044
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mcommand←[0m "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mcwd←[0m C:\Projects\node-opendds-master\node-opendds-master
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mnode -v←[0m v12.22.0
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mnode-gyp -v←[0m v5.1.0
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mnot ok←[0m
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

- Node: 12.22.0
- Node-gyp: 5.1
- VS: 2015

I wonder what is the problem if you can please help me. Thank you!

**Comment by mitza-oci** [comment]
The error is `Undefined variable lib_suffix in ...`, so please try defining that variable.

Note that there are other problems on Windows (see open issue in this repository).

**Comment by mitza-oci** [comment]
Here's an example of `lib_suffix`:
https://github.com/oci-labs/node-opendds/blob/48285c095751137cc43b4ed401516cc31295d825/.github/workflows/build.yml#L203

Windows support should improve when #41 is merged

**Comment by luojinzhang** [comment]
Hi,
Thank you for responding, so, I decided to do it on Linux (Ubuntu 20.04), and tried the demo https://github.com/oci-labs/iiot-demo-opendds first. I got the publisher worked, but the subscriber crashed throwing error: 
`node: symbol lookup error: ../lib/libNexmatix.so: undefined symbol: _ZN2v820EscapableHandleScope6EscapeEPPNS_8internal6ObjectE`
Do you have any idea what might be the problem ?

**Comment by simpsont-oci** [comment]
What versions of node-opendds and OpenDDS are you using here? This looks suspiciously like it's using an older version that didn't make full use of NAN to abstract away differences between node versions.

**Comment by luojinzhang** [comment]
Hi,
It seems that the problem was because of Linux version, I tried it with Ubuntu 18.04 and it worked ! I tried investigating the problem with 20.04 and it was indeed that the symbol `_ZN2v820EscapableHandleScope6EscapeEPPNS_8internal6ObjectE` in libNexmatix.so was undefined somehow. 
Anyway thank you very much guys!
