### ISSUE TITLE
Error when trying to make v8stubs

### ISSUE THREAD

**Issue by e55k4y** [oci-labs/node-opendds#5]
I have installed OpenDDS 3.12 and have compiled and ran the sample code given in OpenDDS examples. I tried to build and run the test provided with node-opendds.
It gave an error
`test_publisher will not be built due to the following missing library: v8stubs`

Then I generated makefile in v8stubs folder with the following command:
`$ACE_ROOT/bin/mpc.pl -type gnuace v8stubs.mpc`
and then tried to build with make command
It threw error #include <v8.h> no such file or directory
So I installed libv8-dev by apt-get install

Now it's throwing error: 
`GNUmakefile: /home/ubuntu/testFolder/node_modules/opendds/tools/v8stubs/GNUmakefile.v8stubs MAKEFLAGS=

g++ -Wno-deprecated-declarations -fvisibility=hidden -fvisibility-inlines-hidden -ggdb -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE   -I/home/ubuntu/OpenDDS-3.12/ACE_wrappers -D__ACE_INLINE__ -I/include/node -I  -c -fPIC -o .shobj/v8stubs.o v8stubs.cpp
v8stubs.cpp:6:16: error: prototype for ‘v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’ does not match any in class ‘v8::Array’
   Local<Array> Array::New(Isolate*, int) { return {}; }
                ^
In file included from v8stubs.cpp:3:0:
/usr/include/v8.h:1758:32: error: candidate is: static v8::Local<v8::Array> v8::Array::New(int)
   V8EXPORT static Local<Array> New(int length = 0);
                                ^
v8stubs.cpp:7:3: error: ‘EscapableHandleScope’ does not name a type
   EscapableHandleScope::EscapableHandleScope(Isolate*) {}
   ^
v8stubs.cpp:8:22: error: ‘EscapableHandleScope’ has not been declared
   internal::Object** EscapableHandleScope::Escape(internal::Object**) {
                      ^
v8stubs.cpp:12:22: error: prototype for ‘v8::internal::Object** v8::HandleScope::CreateHandle(v8::internal::HeapObject*, v8::internal::Object*)’ does not match any in class ‘v8::HandleScope’
   internal::Object** HandleScope::CreateHandle(internal::HeapObject*,
                      ^
In file included from v8stubs.cpp:3:0:
/usr/include/v8.h:468:29: error: candidates are: static v8::internal::Object** v8::HandleScope::CreateHandle(v8::internal::HeapObject*)
   static internal::Object** CreateHandle(internal::HeapObject* value);
                             ^
/usr/include/v8.h:466:29: error:                 static v8::internal::Object** v8::HandleScope::CreateHandle(v8::internal::Object*)
   static internal::Object** CreateHandle(internal::Object* value);
                             ^
v8stubs.cpp:17:18: error: prototype for ‘v8::Local<v8::Integer> v8::Integer::NewFromUnsigned(v8::Isolate*, unsigned int)’ does not match any in class ‘v8::Integer’
   Local<Integer> Integer::NewFromUnsigned(Isolate*, unsigned int) {
                  ^
In file included from v8stubs.cpp:3:0:
/usr/include/v8.h:1393:34: error: candidates are: static v8::Local<v8::Integer> v8::Integer::NewFromUnsigned(uint32_t, v8::Isolate*)
   V8EXPORT static Local<Integer> NewFromUnsigned(uint32_t value, Isolate*);
                                  ^
/usr/include/v8.h:1391:34: error:                 static v8::Local<v8::Integer> v8::Integer::NewFromUnsigned(uint32_t)
   V8EXPORT static Local<Integer> NewFromUnsigned(uint32_t value);
                                  ^
v8stubs.cpp:20:18: error: prototype for ‘v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int)’ does not match any in class ‘v8::Integer’
   Local<Integer> Integer::New(Isolate*, int) { return {}; }
                  ^
In file included from v8stubs.cpp:3:0:
/usr/include/v8.h:1392:34: error: candidates are: static v8::Local<v8::Integer> v8::Integer::New(int32_t, v8::Isolate*)
   V8EXPORT static Local<Integer> New(int32_t value, Isolate*);
                                  ^
/usr/include/v8.h:1390:34: error:                 static v8::Local<v8::Integer> v8::Integer::New(int32_t)
   V8EXPORT static Local<Integer> New(int32_t value);
                                  ^
v8stubs.cpp:22:45: error: no ‘v8::Local<v8::Context> v8::Isolate::GetCurrentContext()’ member function declared in class ‘v8::Isolate’
   Local<Context> Isolate::GetCurrentContext() { return {}; }
                                             ^
v8stubs.cpp:23:17: error: prototype for ‘v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)’ does not match any in class ‘v8::Number’
   Local<Number> Number::New(Isolate*, double) { return {}; }
                 ^
In file included from v8stubs.cpp:3:0:
/usr/include/v8.h:1377:33: error: candidate is: static v8::Local<v8::Number> v8::Number::New(double)
   V8EXPORT static Local<Number> New(double value);
                                 ^
v8stubs.cpp:24:17: error: prototype for ‘v8::Local<v8::Object> v8::Object::New(v8::Isolate*)’ does not match any in class ‘v8::Object’
   Local<Object> Object::New(Isolate*) { return {}; }
                 ^
In file included from v8stubs.cpp:3:0:
/usr/include/v8.h:1724:33: error: candidate is: static v8::Local<v8::Object> v8::Object::New()
   V8EXPORT static Local<Object> New();
                                 ^
v8stubs.cpp:25:8: error: prototype for ‘bool v8::Object::Set(unsigned int, v8::Local<v8::Value>)’ does not match any in class ‘v8::Object’
   bool Object::Set(unsigned int, Local<Value>) { return false; }
        ^
In file included from v8stubs.cpp:3:0:
/usr/include/v8.h:1487:17: error: candidates are: bool v8::Object::Set(uint32_t, v8::Handle<v8::Value>)
   V8EXPORT bool Set(uint32_t index,
                 ^
/usr/include/v8.h:1483:17: error:                 bool v8::Object::Set(v8::Handle<v8::Value>, v8::Handle<v8::Value>, v8::PropertyAttribute)
   V8EXPORT bool Set(Handle<Value> key,
                 ^
v8stubs.cpp:26:8: error: prototype for ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ does not match any in class ‘v8::Object’
   bool Object::Set(Local<Value>, Local<Value>) { return false; }
        ^
In file included from v8stubs.cpp:3:0:
/usr/include/v8.h:1487:17: error: candidates are: bool v8::Object::Set(uint32_t, v8::Handle<v8::Value>)
   V8EXPORT bool Set(uint32_t index,
                 ^
/usr/include/v8.h:1483:17: error:                 bool v8::Object::Set(v8::Handle<v8::Value>, v8::Handle<v8::Value>, v8::PropertyAttribute)
   V8EXPORT bool Set(Handle<Value> key,
                 ^
v8stubs.cpp:27:48: error: no ‘v8::Local<v8::Value> v8::Object::SlowGetInternalField(int)’ member function declared in class ‘v8::Object’
   Local<Value> Object::SlowGetInternalField(int) { return {}; }
                                                ^
v8stubs.cpp:28:3: error: ‘MaybeLocal’ does not name a type
   MaybeLocal<String> String::NewFromTwoByte(Isolate*, const uint16_t*,
   ^
v8stubs.cpp:32:3: error: ‘MaybeLocal’ does not name a type
   MaybeLocal<String> String::NewFromUtf8(Isolate*, const char*,
   ^
v8stubs.cpp:36:25: error: no ‘void v8::V8::ToLocalEmpty()’ member function declared in class ‘v8::V8’
   void V8::ToLocalEmpty() {}
                         ^
v8stubs.cpp:37:3: error: ‘MaybeLocal’ does not name a type
   MaybeLocal<Int32> Value::ToInt32(Local<Context>) const { return {}; }
   ^
v8stubs.cpp:38:3: error: ‘MaybeLocal’ does not name a type
   MaybeLocal<Uint32> Value::ToUint32(Local<Context>) const { return {}; }
   ^
make: *** [.shobj/v8stubs.o] Error 1`

**Comment by mitza-oci** [comment]
You mentioned apt-get, so I suppose this is some debian-based linux distribution.  Please provide more information on your system such as the distro version and versions of important packages (gcc, v8, node, npm, etc.).

The build on Travis-CI passed (https://travis-ci.org/oci-labs/node-opendds) so it may help to take a look at that and see what's different on your system.

**Comment by e55k4y** [comment]
Do you have any documented steps on how to run the test for node-opendds? Actually I am not sure if I am doing the build or the run correctly.

**Comment by mitza-oci** [comment]
You can use the configuration on Travis CI (see prior post for link) for an example of running the test.

**Comment by e55k4y** [comment]
I followed exact steps as given in Travis build and found out the issue.
When I run make, -stdc=c++11 flag is not there, as it seems to be in the Travis build log. I don't know why this is happening. Any help would be appreciated.

**Comment by mitza-oci** [comment]
Check if the ACE+TAO version you are using matches what's used by the Travis build.  If you are using a different version, it can still be made to work but could require different configuration options.

**Comment by e55k4y** [comment]
Seems that was the problem. Thanks a lot. Closing the issue.
