### ISSUE TITLE
Provide usage example

### ISSUE THREAD

**Issue by wzr1337** [oci-labs/node-opendds#53]
I am learning DDS right now.. played with the c++ Messenger example from the official docs..

Would be nice to have an example here too

**Comment by simpsont-oci** [comment]
We're in the process of getting an article ready on this very topic, which I will post back when it gets published and add a link to the README. But for now, check out https://github.com/oci-labs/node-opendds-rest-demo

**Comment by simpsont-oci** [comment]
I've updated the README with the above link and a link to [the article discussing it](https://objectcomputing.com/resources/publications/sett/custom-bridges-between-restful-web-services-and-dds). Hopefully that's helpful by way of an additional example of what's possible with node-opendds.
